{
 "title": "USA Birth Names",
 "time": { "from": "1970-01-01T00:00:01.920Z", "to": "1970-01-01T00:00:01.951Z" },
 "panels": [
  {
   "title": "Participants",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() as time,\n  sum(count) as value\nFROM\n  state_names\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center\">  <h1>Birth Names Dashboard</h1>  <img src=\"/public/img/babies.png\" style=\"width:50%;\"></div>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Gender",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() as time,\n  \"gender\" as state,\n  sum(count) as value\nFROM\n  state_names\ngroup by gender\n\n\n"
    }
   ]
  },
  {
   "title": "Girls",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nNOW() as time,\n  name,\n  sum(count) as count\nFROM\n  national_names\nWHERE gender = 'F'  \nGROUP BY name\nORDER BY count desc\nlimit 12\n\n"
    }
   ]
  },
  {
   "title": "Girl Name Cloud",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS \"time\",\n  name AS metric,\n  sum(count) as count\nFROM national_names\nWHERE gender = 'F'\nGROUP BY name\nORDER BY count desc\nlimit 100"
    }
   ]
  },
  {
   "title": "Boys",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nNOW() as time,\n  name,\n  sum(count) as count\nFROM\n  national_names\nWHERE gender = 'M'  \nGROUP BY name\nORDER BY count desc\nlimit 12\n\n"
    }
   ]
  },
  {
   "title": "BoyName Cloud",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS \"time\",\n  name AS metric,\n  sum(count) as count\nFROM national_names\nWHERE gender = 'M'\nGROUP BY name\nORDER BY count desc\nlimit 100"
    }
   ]
  },
  {
   "title": "Names by States",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() as time,\n  \"state\" as state,\n  sum(count) as value\nFROM\n  state_names\ngroup by state\norder by value desc\nlimit 20\n"
    }
   ]
  }
 ]
}